-- lua\modules\core\bone\constants.lua
ENP = ENP or {}
ENP.CONSTANTS = ENP.CONSTANTS or {}
ENP.CONSTANTS.EPS = 1e-8
ENP.CONSTANTS.PROXY_CLASS = "enp_proxy"

ENP.CONSTANTS.PRIORITY_FIRST = -1e4
ENP.CONSTANTS.PRIORITY_LAST = 1e4
